### ISSUE TITLE
Unable to achieve alignment after 20k iterations on Hindi Speech dataset of ~20 hours.

### ISSUE THREAD

**Issue by prajwalkr** [NVIDIA/tacotron2#160]
My hparams.py file is in the default setting. My audio files are 1-10 seconds long with no silences at the ends.

The model has been trained on >20K iterations with a batch size of 16 on two GPUs (so effective batch size is 32). 

Replaced the symbols in the symbols.py file with all unique Hindi characters in my dataset. Using basic_cleaners. 

Here is the poor alignment image:
![image](https://user-images.githubusercontent.com/8796788/53860043-ac39e400-4005-11e9-84bf-1be4084a73a8.png)

Mel predicted:
![image](https://user-images.githubusercontent.com/8796788/53861811-3f294d00-400b-11e9-983c-30e83802c2ec.png)

Mel target:
![image](https://user-images.githubusercontent.com/8796788/53861822-49e3e200-400b-11e9-8e5c-ca87e8aa3c24.png)

Please help me understand what I could be doing wrong. Thanks in advance.

**Comment by rafaelvalle** [comment]
We made changes to the repo to make it easier to start a new model from our model weights.
It should give you better results quicker and with less data.
https://github.com/NVIDIA/tacotron2/issues/162#issuecomment-473481824

**Comment by srijan14** [comment]
@prajwalkr Did you had a change to do some experimentation with Hindi. Needed some help.
Can you share the vocab that you used for Hindi. I am not sure if just adding the hindi vocab characters in symbols.py is enough because in devnagri some characters take 8bytes (one with the sign) and in general what i saw in python get's splitted in two characters. So does it make any issue while training?
