### ISSUE TITLE
What is the main reason behind removing the wavenet ? 

### ISSUE THREAD

**Issue by shamanez** [NVIDIA/tacotron2#179]

**Comment by rafaelvalle** [comment]
"WaveGlow combines insights from Glow and WaveNet in order to provide fast, efficient and high-quality audio synthesis, without the need for auto-regression. WaveGlow is implemented using only a single network, trained using only a single cost function: maximizing the likelihood of the training data, which makes the training procedure simple and stable."

https://github.com/NVIDIA/waveglow/
