### ISSUE TITLE
waveglow： ImportError: cannot import name 'init_distributed'

### ISSUE THREAD

**Issue by 201402** [NVIDIA/tacotron2#286]
File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code                                
   mod_name, mod_spec, pkg_name, script_name)                                                                                           
 File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code                                       
   exec(code, run_globals)                                                                                                              
 File "D:\GitHub\waveglow\train.py", line 33, in <module>                                                                               
   from distributed import init_distributed, apply_gradient_allreduce, reduce_tensor                                                    
mportError: cannot import name 'init_distributed'                                                                                       
   return _DataLoaderIter(self)                                                                                                         
 File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__   
   w.start()                                                                                                                            

When I run the train.py， I get the error, Anyone can help? Thanks

**Comment by rafaelvalle** [comment]
You need to initialize the waveglow module:
```Initialize submodule: git submodule init; git submodule update```

**Comment by zombodotcom** [comment]
this does not fix the issue.

**Comment by Xianchao-Wu** [comment]
```
#from distributed import init_distributed, apply_gradient_allreduce, reduce_tensor
```
@zombodotcom I think you can simply comment this line since it is only for multi-gpu (i.e., when num_gpus > 1) training. 
These three functions are used in three spaces and you can move the ```import``` to the respective positions:

```
    if num_gpus > 1:
        from distributed import init_distributed
        init_distributed(rank, num_gpus, group_name, **dist_config)
```

```
    if num_gpus > 1:
        from distributed import apply_gradient_allreduce
        model = apply_gradient_allreduce(model)
```

```
            if num_gpus > 1:
                from distributed import reduce_tensor
                reduced_loss = reduce_tensor(loss.data, num_gpus).item()
```

**Comment by Xianchao-Wu** [comment]
@zombodotcom 
Actually, the bug comes from (1) python distributed.py -> (2) distributed.py call train.py -> (3) train.py (however, which) import back distributed again... Which is a bug actually. 

Solution: you can simply:
`cp distributed.py dis_methods.py`
and change 
`from distributed import init_distributed, apply_gradient_allreduce, reduce_tensor`  into
`from dis_methods import init_distributed, apply_gradient_allreduce, reduce_tensor`.
This shall solve the problem. 

[for sure, another solution is that, you can use tacotron2's train.py and distributed.py to import these three methods.
Alike: 
`from tacotron2.distributed import apply_gradient_allreduce`
`from tacotron2.train import init_distributed, reduce_tensor`
]

Also, @rafaelvalle can have a look at this bug.
