### ISSUE TITLE
Why do we need upper letters in text/symbols.py ?

### ISSUE THREAD

**Issue by EuphoriaCelestial** [NVIDIA/tacotron2#427]
As the title, I really wonder why do we need upper letters in `text/symbols.py` file?
Doesnt it will increase the model size thus requires longer training time and slower the inference performance? All pre-defined text cleaners convert text to lower case, so if I am right, there is nothing to do with those upper letter in the alphabet. 
In fact, I trained all my model with only lower case letters in alphabet and it work just fine. Should we remove it in the master branch?

**Comment by CookiePPP** [comment]
with float32, you have 4 bytes per tensor element.
```python
        symbols_embedding_dim=512,
```
By default the model uses 512 elements per char, so each letter uses 2KB.
There are 26 upper case letters, and they're only taken from the embedding when called, so by default you lose 52KB of VRAM to the extra letters.

They have no impact on performance since the embedding layer is just a lookup table.

https://stackoverflow.com/a/37120864 <- random post also saying that adding elements to a list (aka tensor) does not increase time to find/load each element.

---

What I'm saying is, there's no point removing those symbols. It will break backwards compatibility without giving any worthwhile benefits.

**Comment by EuphoriaCelestial** [comment]
> It will break backwards compatibility

Can you explain what is backwards compatibility? why do we need it here?
Now I understand there is no benefit when remove those symbol, but why do they added them in the first place?

**Comment by CookiePPP** [comment]
@EuphoriaCelestial 
The pretrained models will need to be modified if you change the default params.

https://github.com/NVIDIA/tacotron2/blob/master/inference.ipynb
```python
hparams = create_hparams()
```

The text symbols are loaded from the repo, not packaged with the model checkpoints. Changing symbols.py in the master branch will break every already trained model that uses this repo.

**Comment by EuphoriaCelestial** [comment]
> @EuphoriaCelestial
> The pretrained models will need to be modified if you change the default params.
> 
> https://github.com/NVIDIA/tacotron2/blob/master/inference.ipynb
> 
> ```python
> hparams = create_hparams()
> ```
> 
> The text symbols are not packaged with the model checkpoints. Changing symbols.py in the master branch will break every model that uses this repo.

Ah yes, I get the backwards compatibility part. 
But why do they added upper letters since the first version, first model, first branch? There must be a reason

**Comment by CookiePPP** [comment]
https://github.com/keithito/tacotron/blob/479976b6c532ccb0410f914ee7d2e879d0c7d205/text/symbols.py

You will need to ask keithito, the text preprocessor is taken from his code.

**Comment by EuphoriaCelestial** [comment]
Okay, I am creating a new issue for him. Thank you for explaining!
